name: Limpieza y Notificaciones

on:
  schedule:
    - cron: '*/30 * * * *'  # Cada 30 minutos
  workflow_dispatch:        # También se puede correr manualmente

jobs:
  tareas-programadas:
    runs-on: ubuntu-latest
    steps:
      - name: Limpiar eventos vencidos
        run: curl -X DELETE "https://www.jugahora.com.ar/api/eventos/cleanup"

      - name: Limpiar partidos vencidos
        run: curl -X DELETE "https://www.jugahora.com.ar/api/matches/cleanup"

      - name: Enviar notificaciones
        run: curl -X GET "https://www.jugahora.com.ar/api/matches/reminder"
