name: Notificaciones de Partidos

on:
  schedule:
    - cron: '0 * * * *'  # Cada hora en UTC
  workflow_dispatch:  # Para ejecutarlo manualmente

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar a la API
        run: curl -X GET "https://jugahora.vercel.app/api/matches/reminder"
